# Data preprocessing

This notebook contains preprocessing of the four data tables we have chosen. To check the data quality and missing values, we used Sweetviz. There were no missing values:) We decided to split each dataset in a 7:3 ratio (train:test) and later scale all values in each new dataset using the scale_dataframes function.

In [1]:
import numpy as np
import pandas as pd

# import sweetviz as sv - only to check data quality
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
def scale_dataframes(train_df, test_df, target_column):
  
    numeric_cols = [col for col in train_df.columns if col != target_column]
    
    scaler = StandardScaler()
    scaler.fit(train_df[numeric_cols])
    
    train_scaled = train_df.copy()
    test_scaled = test_df.copy()
    
    train_scaled[numeric_cols] = scaler.transform(train_df[numeric_cols])
    test_scaled[numeric_cols] = scaler.transform(test_df[numeric_cols])
    
    return train_scaled, test_scaled

## Heart Attack dataframe

 Target variable -> class

In [3]:
heart_df = pd.read_csv('Data/Heart-Attack.csv')
heart_df.head()

,age,gender,impluse,pressurehight,pressurelow,glucose,kcm,troponin,class
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative

In [4]:
# raport_1 = sv.analyze(heart_df)
# raport_1.show_html("raport_1_sweetviz.html")

In [5]:
heart_df['class'] = heart_df['class'].map({'negative': 0, 'positive': 1})

In [6]:
heart_train_df, heart_test_df = train_test_split(heart_df, test_size=0.25, stratify=heart_df['class'], random_state=42)

In [7]:
heart_train_df, heart_test_df = scale_dataframes(heart_train_df, heart_test_df, target_column='class')

In [8]:
heart_train_df.to_csv('Data/heart_train.csv', index=False)
heart_test_df.to_csv('Data/heart_test.csv', index=False)

## Mushrooms dataframe

Target Variable -> class

All values are categorical, so we use OneHotEncoder and we don't scale it.

In [9]:
mushrooms_df = pd.read_csv('Data/mushrooms.csv')
mushrooms_df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [10]:
# raport_2 = sv.analyze(mushrooms_df)
# raport_2.show_html("raport_2_sweetviz.html")

In [11]:
mushrooms_df['class'] = mushrooms_df['class'].map({'p': 0, 'e': 1})

In [12]:
y = mushrooms_df["class"]
X = mushrooms_df.drop(columns=['class'])

encoder = OneHotEncoder(sparse_output=False)  
X_encoded = encoder.fit_transform(X)

X_encoded_df = pd.DataFrame(X_encoded, columns=encoder.get_feature_names_out(X.columns))
mushrooms_df = pd.concat([X_encoded_df, y.reset_index(drop=True)], axis=1)

In [13]:
mushrooms_train_df, mushrooms_test_df = train_test_split(mushrooms_df, test_size=0.25, stratify=mushrooms_df['class'], random_state=42)

In [14]:
mushrooms_train_df, mushrooms_test_df = scale_dataframes(mushrooms_train_df, mushrooms_test_df, target_column='class')

In [15]:
mushrooms_train_df.to_csv('Data/mushrooms_train.csv', index=False)
mushrooms_test_df.to_csv('Data/mushrooms_test.csv', index=False)

## Rice dataframe

Target variable -> Class

In [16]:
rice_df = pd.read_csv('Data/riceClassification.csv')
rice_df.head()

,id,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,EquivDiameter,Extent,Perimeter,Roundness,AspectRation,Class
0,1,4537,92.229316,64.012769,0.719916,4677,76.004525,0.657536,273.085,0.764510,1.440796,1
1,2,2872,74.691881,51.400454,0.725553,3015,60.471018,0.713009,208.317,0.831658,1.453137,1
2,3,3048,76.293164,52.043491,0.731211,3132,62.296341,0.759153,210.012,0.868434,1.465950,1
3,4,3073,77.033628,51.928487,0.738639,3157,62.551300,0.783529,210.657,0.870203,1.483456,1
4,5,3693,85.124785,56.374021,0.749282,3802,68.571668,0.769375,230.332,0.874743,1.510000,1

In [17]:
# raport_3 = sv.analyze(rice_df)
# raport_3.show_html("raport_3_sweetviz.html")

In [18]:
rice_df = rice_df.drop(columns = ["id"])

In [19]:
rice_train_df, rice_test_df = train_test_split(rice_df, test_size=0.25, stratify=rice_df['Class'], random_state=42)

In [20]:
rice_train_df, rice_test_df = scale_dataframes(rice_train_df, rice_test_df, target_column='Class')

In [21]:
rice_train_df.to_csv('Data/rice_train.csv', index=False)
rice_test_df.to_csv('Data/rice_test.csv', index=False)

## Wine dataframe

Target variable -> type

In [22]:
wine_df = pd.read_csv('Data/wine_quality_merged.csv')
wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [23]:
# raport_4 = sv.analyze(wine_df)
# raport_4.show_html("raport_4_sweetviz.html")

In [24]:
wine_df['type'] = wine_df['type'].map({'red': 0, 'white': 1})

In [25]:
wine_train_df, wine_test_df = train_test_split(wine_df, test_size=0.25, stratify=wine_df['type'], random_state=42)

In [26]:
wine_train_df, wine_test_df = scale_dataframes(wine_train_df, wine_test_df, target_column='type')

In [27]:
wine_train_df.to_csv('Data/wine_train.csv', index=False)
wine_test_df.to_csv('Data/wine_test.csv', index=False)